### ISSUE TITLE
Respond to server channel slash commands

### ISSUE THREAD

**Issue by abl** [abl/cs5500-f21-starterbot#1]
As a developer,
I want to be able to talk to the bot inside of a server
So that I can develop server-scale, multi-user, interactions.

Right now, the bot will respond in DMs but will not install a slash command handler in servers where it has been invited. This does not seem to be expected behavior and many interesting interactions (such as shared leaderboards) only make sense when interacting with the bot in a shared channel.

 * https://canary.discord.com/developers/docs/interactions/slash-commands

Exit criteria:

- [ ] StarterBot#4243 has been invited to the CS 5500 F21 class-wide discord server
- [ ] StarterBot#4243 responds to the `/say` command in the general channel of the server
- [ ] StarterBot#4243 still responds to DMs that include the `/say` command

**Comment by qhb1001** [comment]
I solved this bug with the help of this link: https://stackoverflow.com/questions/68292025/how-to-use-slash-command-in-channel-with-jda

Hope it helps :)
